{
 "title": "OpenVPN Server",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(openvpn_up, job)" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(openvpn_up{job=\"openvpn-metrics\"}, status_path)"
   },
   {
    "name": "client",
    "label": "Client",
    "query": "label_values(openvpn_server_client_received_bytes_total{job=~\"$job\"}, common_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "GitHub",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "content": "# [![GitHub](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white)](https://github.com/B4DCATs/openvpn_exporter)\n\n**OpenVPN Exporter**\n\nSource code and documentation"
  },
  {
   "title": "Discord",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "content": "# [![Discord](https://img.shields.io/discord/1411852800241176616?style=for-the-badge&logo=discord&logoColor=white&label=Discord)](https://discord.gg/VMKdhujjCW)\n\n**Community Support**\n\nJoin our Discord server for help and discussions"
  },
  {
   "title": "Top Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(count_values(\"connection_time\", count_over_time(openvpn_server_client_received_bytes_total{job=~\"$job\", common_name=~\"$client\"}[1d]))by(common_name))by(common_name)>1)",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openvpn_up{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(label_replace(openvpn_server_client_received_bytes_total{job=~\"$job\", common_name=~\"$client\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, real_address, virtual_address))"
    },
    {
     "expr": "sum(label_replace(openvpn_server_client_sent_bytes_total{job=~\"$job\", common_name=~\"$client\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, real_address, virtual_address)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openvpn_openvpn_server_connected_clients{job=~\"$job\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds{job=~\"$job\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{common_name=~\"server[0-9].example.com\"}) or absent(count(openvpn_server_client_received_bytes_total{common_name=~\"server[0-9].example.com\"}))-1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{common_name=~\"[a-z]+ee\"}) or absent(count(openvpn_server_client_received_bytes_total{common_name=~\"[a-z]+ee\"}))-1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{job=~\"$job\", common_name=~\"$client\"}[1d])+increase(openvpn_server_client_sent_bytes_total{job=~\"$job\", common_name=~\"$client\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Top 6 Client Network Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_received_bytes_total{job=~\"$job\", common_name=~\"$client\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Rx"
    },
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_sent_bytes_total{job=~\"$job\", common_name=~\"$client\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Tx"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_received_bytes_total{job=~\"$job\", common_name=~\"$client\"}[2m]))by(common_name)))",
     "legendFormat": "Rx - Others"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_sent_bytes_total{job=~\"$job\", common_name=~\"$client\"}[1m]))by(common_name)))",
     "legendFormat": "Tx - Others"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort(sum(increase(openvpn_server_client_received_bytes_total{job=~\"$job\", common_name=~\"$client\"}[1d])+increase(openvpn_server_client_sent_bytes_total{job=~\"$job\", common_name=~\"$client\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Clients" }
   ],
   "targets": [
    {
     "expr": "sum(openvpn_openvpn_server_connected_clients{job=~\"$job\"})",
     "legendFormat": "Connected OpenVPN Clients"
    }
   ]
  }
 ]
}