version: '3.8'

services:
  openvpn-exporter:
    image: ghcr.io/b4dcats/openvpn_exporter:latest
    container_name: openvpn-exporter
    restart: unless-stopped
    ports:
      - "9176:9176"
    volumes:
      # Mount OpenVPN status files (read-only)
      - /var/log/openvpn:/var/log/openvpn:ro
      - /etc/openvpn:/etc/openvpn:ro
    environment:
      - LISTEN_ADDRESS=${LISTEN_ADDRESS:-:9176}
      - TELEMETRY_PATH=${TELEMETRY_PATH:-/metrics}
      - STATUS_PATHS=${STATUS_PATHS:-/var/log/openvpn/status.log}
      - IGNORE_INDIVIDUALS=${IGNORE_INDIVIDUALS:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ALLOWED_IPS=${ALLOWED_IPS:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9176/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    init: true
