# Prometheus configuration for OpenVPN monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # OpenVPN Exporter
  - job_name: 'openvpn-metrics'
    static_configs:
      - targets: ['openvpn-exporter:9176']
    scrape_interval: 30s
    metrics_path: '/metrics'
    honor_labels: true

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
